settings:
  language: en

cooldown:
  event-start: 300
  command: 5

events:
  enabled: true
  min-interval: 180
  max-interval: 600
  coin-rain:
    chance: 100
    reward:
      min: 1.0
      max: 5.0
    drop-interval-ticks: 10
    velocity-multiplier: 0.4
  lightning-storm:
    chance: 100
  tnt-rain:
    chance: 100
  mob-swarm:
    chance: 100
  random-teleport:
    chance: 100
  fire-feet:
    chance: 100
  freeze:
    chance: 100
  black-hole:
    chance: 100
  random-effects:
    chance: 100
  target-player:
    chance: 100
  spin:
    chance: 100

streak-rewards:
  milestones:
    #modes vault/command/item
    #vaules for command and item must be in "" (exp value: "DIAMOND 3")
    "3":
      mode: vault
      value: 5.0
    "5":
      mode: vault
      value: 15.0
    "10":
      mode: vault
      value: 50.0

voting:
  cost: 100.0

announcements:
  times:
    - 10
    - 5
    - 1

queue:
  retry-delay-seconds: 15

bossbar:
  enabled: true
  color: BLUE
  style: SOLID

update-check:
  enabled: true
  check-on-startup: true
  notify-on-join: true

multiworld:
  enabled: true
  allowed-worlds:
    - world
    - event_world
